import React, { createContext, useContext, useState } from "react";

const translations = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.farmers": "Farmers Directory",
    "nav.yield": "Yield & Crop Analysis",
    "nav.pest": "Pest & Disease Tracking",
    "nav.market": "Market Prices",
    "nav.alerts": "Alerts & Notifications",
    "nav.schemes": "Schemes & Subsidies",
    "nav.reports": "Reports & Insights",
    "nav.settings": "Settings",
    "login.title": "Government of Odisha",
    "login.subtitle": "Electronics & IT Department",
    "login.signin": "Sign In to Portal",

    settings: "Settings",
    manageSystemPreferences: "Manage your account and system preferences",
    systemOnline: "System Online",
    profile: "Profile",
    language: "Language",
    notifications: "Notifications",
    security: "Security",
    system: "System",
    profileInformation: "Profile Information",
    updateProfileDetails:
      "Update your personal details and contact information",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    phone: "Phone",
    department: "Department",
    saveChanges: "Save Changes",
    languagePreferences: "Language Preferences",
    selectPreferredLanguage: "Select your preferred language for the interface",
    selected: "Selected",
    additionalSettings: "Additional Settings",
    dateFormat: "Date Format",
    chooseDateFormat: "Choose your preferred date format",
    timeFormat: "Time Format",
    choose12or24Hour: "Choose between 12-hour or 24-hour format",
    notificationSettings: "Notification Settings",
    manageNotificationPreferences:
      "Manage how you receive notifications and alerts",
    emailNotifications: "Email Notifications",
    receiveEmailUpdates: "Receive updates and alerts via email",
    smsNotifications: "SMS Notifications",
    receiveSMSAlerts: "Receive important alerts via SMS",
    pushNotifications: "Push Notifications",
    receivePushNotifications: "Receive browser push notifications",
    systemAlerts: "System Alerts",
    receiveSystemAlerts: "Receive critical system alerts",
    notificationTiming: "Notification Timing",
    quietHoursStart: "Quiet Hours Start",
    quietHoursEnd: "Quiet Hours End",
    securitySettings: "Security Settings",
    manageAccountSecurity: "Manage your account security and authentication",
    currentPassword: "Current Password",
    enterCurrentPassword: "Enter your current password",
    newPassword: "New Password",
    enterNewPassword: "Enter your new password",
    confirmPassword: "Confirm Password",
    confirmNewPassword: "Confirm your new password",
    updatePassword: "Update Password",
    twoFactorAuthentication: "Two-Factor Authentication",
    enable2FA: "Enable 2FA",
    addExtraSecurityLayer: "Add an extra layer of security to your account",
    setup2FA: "Setup 2FA",
    sessionManagement: "Session Management",
    currentSession: "Current Session",
    active: "Active",
    current: "Current",
    logoutAllDevices: "Logout All Devices",
    systemConfiguration: "System Configuration",
    manageSystemSettings: "Manage system-wide settings and configurations",
    dataExport: "Data Export",
    exportSystemData: "Export system data for backup or analysis",
    exportData: "Export Data",
    dataImport: "Data Import",
    importSystemData: "Import data from external sources",
    importData: "Import Data",
    systemBackup: "System Backup",
    createSystemBackup: "Create a complete system backup",
    createBackup: "Create Backup",
    databaseMaintenance: "Database Maintenance",
    optimizeDatabase: "Optimize database performance",
    optimize: "Optimize",
    systemInformation: "System Information",
    version: "Version",
    lastUpdate: "Last Update",
    uptime: "Uptime",
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    storageUsed: "Storage Used",
  },
  hi: {
    "nav.dashboard": "डैशबोर्ड",
    "nav.farmers": "किसान निर्देशिका",
    "nav.yield": "उत्पादन और फसल विश्लेषण",
    "nav.pest": "कीट और रोग ट्रैकिंग",
    "nav.market": "बाजार मूल्य",
    "nav.alerts": "अलर्ट और सूचनाएं",
    "nav.schemes": "योजनाएं और सब्सिडी",
    "nav.reports": "रिपोर्ट और अंतर्दृष्टि",
    "nav.settings": "सेटिंग्स",
    "login.title": "ओडिशा सरकार",
    "login.subtitle": "इलेक्ट्रॉनिक्स और आईटी विभाग",
    "login.signin": "पोर्टल में साइन इन करें",

    settings: "सेटिंग्स",
    manageSystemPreferences: "अपने खाते और सिस्टम प्राथमिकताओं का प्रबंधन करें",
    systemOnline: "सिस्टम ऑनलाइन",
    profile: "प्रोफ़ाइल",
    language: "भाषा",
    notifications: "सूचनाएं",
    security: "सुरक्षा",
    system: "सिस्टम",
    profileInformation: "प्रोफ़ाइल जानकारी",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    email: "ईमेल",
    phone: "फोन",
    department: "विभाग",
    saveChanges: "परिवर्तन सहेजें",
  },
  or: {
    "nav.dashboard": "ଡ୍ୟାସବୋର୍ଡ",
    "nav.farmers": "କୃଷକ ନିର୍ଦେଶିକା",
    "nav.yield": "ଅମଳ ଏବଂ ଫସଲ ବିଶ୍ଳେଷଣ",
    "nav.pest": "କୀଟ ଏବଂ ରୋଗ ଟ୍ରାକିଂ",
    "nav.market": "ବଜାର ମୂଲ୍ୟ",
    "nav.alerts": "ସତର୍କତା ଏବଂ ବିଜ୍ଞପ୍ତି",
    "nav.schemes": "ଯୋଜନା ଏବଂ ସବସିଡି",
    "nav.reports": "ରିପୋର୍ଟ ଏବଂ ଅନ୍ତର୍ଦୃଷ୍ଟି",
    "nav.settings": "ସେଟିଂସ",
    "login.title": "ଓଡ଼ିଶା ସରକାର",
    "login.subtitle": "ଇଲେକ୍ଟ୍ରୋନିକ୍ସ ଏବଂ ଆଇଟି ବିଭାଗ",
    "login.signin": "ପୋର୍ଟାଲରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",

    settings: "ସେଟିଂସ",
    manageSystemPreferences: "ଆପଣଙ୍କ ଖାତା ଏବଂ ସିଷ୍ଟମ ପସନ୍ଦ ପରିଚାଳନା କରନ୍ତୁ",
    systemOnline: "ସିଷ୍ଟମ ଅନଲାଇନ",
    profile: "ପ୍ରୋଫାଇଲ",
    language: "ଭାଷା",
    notifications: "ବିଜ୍ଞପ୍ତି",
    security: "ସୁରକ୍ଷା",
    system: "ସିଷ୍ଟମ",
    profileInformation: "ପ୍ରୋଫାଇଲ ସୂଚନା",
    firstName: "ପ୍ରଥମ ନାମ",
    lastName: "ଶେଷ ନାମ",
    email: "ଇମେଲ",
    phone: "ଫୋନ",
    department: "ବିଭାଗ",
    saveChanges: "ପରିବର୍ତ୍ତନ ସଞ୍ଚୟ କରନ୍ତୁ",
  },
  bn: {
    settings: "সেটিংস",
    profile: "প্রোফাইল",
    language: "ভাষা",
    notifications: "বিজ্ঞপ্তি",
    security: "নিরাপত্তা",
    system: "সিস্টেম",
  },
  te: {
    settings: "సెట్టింగులు",
    profile: "ప్రొఫైల్",
    language: "భాష",
    notifications: "నోటిఫికేషన్లు",
    security: "భద్రత",
    system: "సిస్టమ్",
  },
  ta: {
    settings: "அமைப்புகள்",
    profile: "சுயவிவரம்",
    language: "மொழி",
    notifications: "அறிவிப்புகள்",
    security: "பாதுகாப்பு",
    system: "அமைப்பு",
  },
  ur: {
    settings: "ترتیبات",
    profile: "پروفائل",
    language: "زبان",
    notifications: "اطلاعات",
    security: "سیکیورٹی",
    system: "نظام",
  },
};

const LanguageContext = createContext(undefined);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

